apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8s-program
  name: resources-ms-config-map
data:
  SONGS_MS_URL: "songs-ms-service"
  SONGS_MS_PORT: "8080"
  RESOURCES_DB_URL: "resources-ms-db-statefulset-0.resources-ms-db-service"
  RESOURCES_DB_PORT: "5432"
