apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: resources-ms-service
  labels:
    {{- include "resources-service.labels" . | nindent 4 }}
spec:
  selector:
    app: resources-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
