apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-program
  name: local-ssd-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/volume-test"