apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8s-program
  name: songs-ms-config-map
data:
  SONGS_DB_URL: "songs-ms-db-statefulset-0.songs-ms-db-service"
  SONGS_DB_PORT: "5432"
  SONGS_MS_PORT: "8080"
  init.sql: |
    CREATE TABLE IF NOT EXISTS songs (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255),
        artist VARCHAR(255),
        album VARCHAR(255),
        length VARCHAR(255),
        year VARCHAR(255),
        resourceId INTEGER NOT NULL UNIQUE
    );
