---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: songs-ms-service
spec:
  selector:
    app: songs-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: songs-ms-deployment
  labels:
    app: songs-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-ms
  template:
    metadata:
      labels:
        app: songs-ms
    spec:
      containers:
        - name: songs-ms
          image: songs-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: songs-ms-config-map
            - secretRef:
                name: songs-ms-secrets
          volumeMounts:
            - name: init-script
              mountPath: /etc/config
      volumes:
        - name: init-script
          configMap:
            name: songs-ms-config-map
            items:
              - key: init.sql
                path: init.sql
