apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-service-test-pvc
  namespace: k8s-program
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M